###
GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "title 1",
  "author": "first last",
  "url": "www.idonotexist.com",
  "likes": 1
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "first last",
  "likes": 1
}